import type { AuthorizationRequest, KPIMetric, Notification } from "@/types";

export const MOCK_PATIENTS = [
  {
    id: "p-001",
    name: "Margaret Thompson",
    dob: "1968-04-15",
    memberId: "BCB-4821-009",
    groupId: "GRP-77821",
    plan: "BlueCross PPO Gold",
    payer: "BlueCross BlueShield",
    gender: "Female" as const,
    phone: "(312) 555-0142",
    address: "4821 Lakeview Dr, Chicago, IL 60657",
    primaryCare: "Dr. James Novak",
  },
  {
    id: "p-002",
    name: "Robert Chen",
    dob: "1975-09-22",
    memberId: "AET-2231-077",
    groupId: "GRP-43301",
    plan: "Aetna HMO Silver",
    payer: "Aetna",
    gender: "Male" as const,
    phone: "(415) 555-0299",
    address: "1090 Market St, San Francisco, CA 94102",
    primaryCare: "Dr. Susan Park",
  },
  {
    id: "p-003",
    name: "Linda Okafor",
    dob: "1982-12-08",
    memberId: "UHC-9910-334",
    groupId: "GRP-19284",
    plan: "UnitedHealth Choice Plus",
    payer: "UnitedHealthcare",
    gender: "Female" as const,
    phone: "(713) 555-0871",
    address: "3311 Westheimer Rd, Houston, TX 77098",
    primaryCare: "Dr. David Kim",
  },
];

export const MOCK_PROVIDERS = [
  {
    id: "prov-001",
    name: "Dr. Sarah Mitchell, MD",
    npi: "1234567890",
    specialty: "Orthopedic Surgery",
    organization: "Northwestern Memorial Hospital",
    phone: "(312) 926-2000",
    fax: "(312) 926-2001",
    address: "251 E Huron St, Chicago, IL 60611",
    taxId: "36-1234567",
  },
  {
    id: "prov-002",
    name: "Dr. Kevin Patel, MD",
    npi: "0987654321",
    specialty: "Oncology",
    organization: "UCSF Medical Center",
    phone: "(415) 476-1000",
    fax: "(415) 476-1001",
    address: "505 Parnassus Ave, San Francisco, CA 94143",
    taxId: "94-0987654",
  },
  {
    id: "prov-003",
    name: "Dr. Angela Brooks, MD",
    npi: "1122334455",
    specialty: "Neurology",
    organization: "Houston Methodist Hospital",
    phone: "(713) 790-3333",
    fax: "(713) 790-3334",
    address: "6565 Fannin St, Houston, TX 77030",
    taxId: "74-1122334",
  },
];

export const MOCK_AUTHORIZATIONS: AuthorizationRequest[] = [
  {
    id: "auth-001",
    caseNumber: "PA-2025-08-4821",
    patient: MOCK_PATIENTS[0],
    provider: MOCK_PROVIDERS[0],
    diagnoses: [
      { code: "M17.11", description: "Primary osteoarthritis, right knee", type: "primary" },
      { code: "E11.9", description: "Type 2 diabetes mellitus without complications", type: "secondary" },
    ],
    procedures: [
      { code: "27447", description: "Arthroplasty, knee, condyle and plateau", modifier: "RT", quantity: 1, serviceDate: "2025-09-15", placeOfService: "21 - Inpatient Hospital" },
    ],
    status: "Pending Review",
    priority: "urgent",
    riskLevel: "high",
    submittedAt: "2025-08-17T08:30:00Z",
    updatedAt: "2025-08-17T14:22:00Z",
    dueDate: "2025-08-19T17:00:00Z",
    assignedTo: "Nurse Patricia Lee",
    clinicalNotes: "Patient has failed conservative treatment including PT and NSAIDs for 6 months. X-rays confirm severe joint space narrowing. Surgeon recommends TKR.",
    documents: [
      { id: "doc-001", name: "X-Ray Report - Right Knee.pdf", type: "imaging", uploadedAt: "2025-08-17T08:30:00Z", uploadedBy: "Dr. Sarah Mitchell", size: "2.4 MB" },
      { id: "doc-002", name: "PT Progress Notes.pdf", type: "clinical_note", uploadedAt: "2025-08-17T08:32:00Z", uploadedBy: "Dr. Sarah Mitchell", size: "890 KB" },
      { id: "doc-003", name: "Clinical Documentation.pdf", type: "clinical_note", uploadedAt: "2025-08-17T08:35:00Z", uploadedBy: "Dr. Sarah Mitchell", size: "1.1 MB" },
    ],
    aiRecommendation: {
      decision: "Approve",
      confidence: 87,
      reasoning: "Patient meets medical necessity criteria based on failed conservative therapy (>6 months), radiographic evidence of severe OA, and functional impairment. Policy guidelines align with approval.",
      keyFactors: [
        { name: "Failed Conservative Therapy", impact: "positive", weight: 35, description: "6+ months of PT and NSAID therapy documented" },
        { name: "Radiographic Evidence", impact: "positive", weight: 30, description: "X-ray confirms Kellgren-Lawrence Grade 4 OA" },
        { name: "Functional Impairment", impact: "positive", weight: 20, description: "KOOS score of 38 indicates severe functional limitation" },
        { name: "Comorbidity: T2DM", impact: "negative", weight: 15, description: "Elevated surgical risk due to diabetes, HbA1c needed" },
      ],
      missingInfo: ["HbA1c lab result (required for surgical clearance)", "Anesthesia pre-op evaluation"],
      policyReferences: [
        { id: "pol-001", title: "Total Knee Replacement Policy", section: "Section 3.2 - Medical Necessity Criteria", relevanceScore: 96, excerpt: "Coverage is medically necessary when patient has documented failure of at least 3 months of conservative therapy and radiographic evidence of severe osteoarthritis." },
        { id: "pol-002", title: "Orthopedic Surgery Clinical Criteria", section: "Section 1.4 - Preoperative Requirements", relevanceScore: 82, excerpt: "For patients with diabetes mellitus, HbA1c must be ≤8.0% within 90 days of planned surgery date." },
      ],
      generatedAt: "2025-08-17T14:20:00Z",
      modelVersion: "PriorAuth-AI v2.4.1",
    },
    auditLog: [
      { id: "aud-001", action: "Case Submitted", performedBy: "Dr. Sarah Mitchell", role: "Requesting Provider", timestamp: "2025-08-17T08:30:00Z", details: "Prior authorization request submitted via provider portal" },
      { id: "aud-002", action: "Auto-assigned", performedBy: "System", role: "Automated", timestamp: "2025-08-17T08:31:00Z", details: "Case auto-assigned to Nurse Patricia Lee based on specialty routing" },
      { id: "aud-003", action: "AI Triage Completed", performedBy: "PriorAuth AI v2.4.1", role: "AI System", timestamp: "2025-08-17T14:20:00Z", details: "AI recommendation generated: Approve (87% confidence)" },
      { id: "aud-004", action: "Case Opened", performedBy: "Nurse Patricia Lee", role: "Clinical Reviewer", timestamp: "2025-08-17T14:22:00Z", details: "Clinical reviewer opened the case for review" },
    ],
  },
  {
    id: "auth-002",
    caseNumber: "PA-2025-08-2231",
    patient: MOCK_PATIENTS[1],
    provider: MOCK_PROVIDERS[1],
    diagnoses: [
      { code: "C50.912", description: "Malignant neoplasm of unspecified site of left female breast", type: "primary" },
    ],
    procedures: [
      { code: "96413", description: "Chemotherapy administration, IV infusion technique", modifier: "", quantity: 4, serviceDate: "2025-09-01", placeOfService: "22 - Outpatient Hospital" },
    ],
    status: "Approved",
    priority: "urgent",
    riskLevel: "high",
    submittedAt: "2025-08-15T10:00:00Z",
    updatedAt: "2025-08-16T16:45:00Z",
    dueDate: "2025-08-17T17:00:00Z",
    assignedTo: "Dr. Michael Torres",
    clinicalNotes: "Stage II breast cancer, HER2+. Patient is initiating first-line chemotherapy with Taxol + Herceptin per NCCN guidelines.",
    documents: [
      { id: "doc-004", name: "Pathology Report.pdf", type: "lab_result", uploadedAt: "2025-08-15T10:00:00Z", uploadedBy: "Dr. Kevin Patel", size: "1.8 MB" },
      { id: "doc-005", name: "Oncology Treatment Plan.pdf", type: "clinical_note", uploadedAt: "2025-08-15T10:05:00Z", uploadedBy: "Dr. Kevin Patel", size: "670 KB" },
    ],
    aiRecommendation: {
      decision: "Approve",
      confidence: 98,
      reasoning: "Active malignancy with clear pathological diagnosis. Treatment aligns with NCCN Category 1 guidelines for HER2+ breast cancer.",
      keyFactors: [
        { name: "NCCN Guideline Alignment", impact: "positive", weight: 50, description: "Regimen matches NCCN Category 1 recommendation" },
        { name: "Pathological Confirmation", impact: "positive", weight: 30, description: "Biopsy confirmed HER2+ invasive ductal carcinoma" },
        { name: "Stage-Appropriate Treatment", impact: "positive", weight: 20, description: "Stage II disease, first-line chemo is standard of care" },
      ],
      missingInfo: [],
      policyReferences: [
        { id: "pol-003", title: "Oncology Chemotherapy Policy", section: "Section 2.1 - Breast Cancer Protocols", relevanceScore: 99, excerpt: "Trastuzumab-based regimens are covered for HER2-positive invasive breast cancer per NCCN guidelines." },
      ],
      generatedAt: "2025-08-16T09:00:00Z",
      modelVersion: "PriorAuth-AI v2.4.1",
    },
    auditLog: [
      { id: "aud-005", action: "Case Submitted", performedBy: "Dr. Kevin Patel", role: "Requesting Provider", timestamp: "2025-08-15T10:00:00Z", details: "Prior authorization request submitted" },
      { id: "aud-006", action: "AI Triage Completed", performedBy: "PriorAuth AI v2.4.1", role: "AI System", timestamp: "2025-08-16T09:00:00Z", details: "AI recommendation: Approve (98% confidence)" },
      { id: "aud-007", action: "Final Decision - Approved", performedBy: "Dr. Michael Torres", role: "Medical Director", timestamp: "2025-08-16T16:45:00Z", details: "Approved per AI recommendation and clinical review" },
    ],
  },
  {
    id: "auth-003",
    caseNumber: "PA-2025-08-9910",
    patient: MOCK_PATIENTS[2],
    provider: MOCK_PROVIDERS[2],
    diagnoses: [
      { code: "G35", description: "Multiple sclerosis", type: "primary" },
    ],
    procedures: [
      { code: "J0202", description: "Injection, alemtuzumab, 1 mg (Lemtrada)", modifier: "", quantity: 60, serviceDate: "2025-09-20", placeOfService: "11 - Office" },
    ],
    status: "More Information Required",
    priority: "high",
    riskLevel: "medium",
    submittedAt: "2025-08-16T13:00:00Z",
    updatedAt: "2025-08-17T09:15:00Z",
    dueDate: "2025-08-20T17:00:00Z",
    assignedTo: "Nurse Patricia Lee",
    clinicalNotes: "RRMS patient with 2 relapses in past 12 months. Requesting Lemtrada as second-line DMT after Tecfidera failure.",
    documents: [
      { id: "doc-006", name: "MS Treatment History.pdf", type: "clinical_note", uploadedAt: "2025-08-16T13:00:00Z", uploadedBy: "Dr. Angela Brooks", size: "1.2 MB" },
    ],
    aiRecommendation: {
      decision: "Request More Info",
      confidence: 62,
      reasoning: "Alemtuzumab has a high-risk REMS profile. Documentation of prior DMT failure is incomplete. REMS program enrollment confirmation and MRI results are required.",
      keyFactors: [
        { name: "Prior DMT Failure", impact: "positive", weight: 40, description: "Tecfidera failure claimed but inadequate documentation" },
        { name: "REMS Program Requirement", impact: "negative", weight: 35, description: "Alemtuzumab requires REMS enrollment before dispensing" },
        { name: "Missing MRI", impact: "negative", weight: 25, description: "Current MRI required to confirm active disease" },
      ],
      missingInfo: ["MRI brain/spine within last 6 months", "REMS program enrollment confirmation", "Detailed Tecfidera treatment dates and discontinuation reason"],
      policyReferences: [
        { id: "pol-004", title: "MS Disease-Modifying Therapy Policy", section: "Section 4.3 - High-Efficacy Agents", relevanceScore: 91, excerpt: "Alemtuzumab requires documentation of failure of at least one prior DMT and enrollment in the LEMTRADA REMS program." },
      ],
      generatedAt: "2025-08-17T09:10:00Z",
      modelVersion: "PriorAuth-AI v2.4.1",
    },
    auditLog: [
      { id: "aud-008", action: "Case Submitted", performedBy: "Dr. Angela Brooks", role: "Requesting Provider", timestamp: "2025-08-16T13:00:00Z", details: "PA request submitted" },
      { id: "aud-009", action: "AI Triage Completed", performedBy: "PriorAuth AI v2.4.1", role: "AI System", timestamp: "2025-08-17T09:10:00Z", details: "AI recommendation: Request More Info (62% confidence)" },
      { id: "aud-010", action: "Additional Info Requested", performedBy: "Nurse Patricia Lee", role: "Clinical Reviewer", timestamp: "2025-08-17T09:15:00Z", details: "Requested MRI results, REMS enrollment, and DMT history" },
    ],
  },
  {
    id: "auth-004",
    caseNumber: "PA-2025-08-7734",
    patient: { id: "p-004", name: "James Whitfield", dob: "1955-03-18", memberId: "CIG-7734-002", groupId: "GRP-55221", plan: "Cigna OAP Bronze", payer: "Cigna", gender: "Male", phone: "(404) 555-0311", address: "890 Peachtree St NE, Atlanta, GA 30309", primaryCare: "Dr. Rachel Moore" },
    provider: { id: "prov-004", name: "Dr. Thomas Nguyen, MD", npi: "5566778899", specialty: "Pulmonology", organization: "Emory University Hospital", phone: "(404) 712-7021", fax: "(404) 712-7022", address: "1364 Clifton Rd NE, Atlanta, GA 30322", taxId: "58-5566778" },
    diagnoses: [{ code: "J44.1", description: "COPD with acute exacerbation", type: "primary" }],
    procedures: [{ code: "94667", description: "Manipulation chest wall, each manipulation", modifier: "", quantity: 12, serviceDate: "2025-09-05", placeOfService: "11 - Office" }],
    status: "Denied",
    priority: "normal",
    riskLevel: "low",
    submittedAt: "2025-08-14T09:00:00Z",
    updatedAt: "2025-08-15T11:30:00Z",
    dueDate: "2025-08-17T17:00:00Z",
    assignedTo: "Dr. Sarah Kim",
    clinicalNotes: "Requesting chest PT for COPD management. Patient has home O2.",
    documents: [{ id: "doc-007", name: "Pulmonary Function Test.pdf", type: "lab_result", uploadedAt: "2025-08-14T09:00:00Z", uploadedBy: "Dr. Thomas Nguyen", size: "520 KB" }],
    aiRecommendation: {
      decision: "Deny",
      confidence: 79,
      reasoning: "Chest PT for COPD is not covered under the patient's plan for outpatient setting. Plan benefit exclusion applies. Recommend appeal with home-setting documentation.",
      keyFactors: [
        { name: "Plan Exclusion", impact: "negative", weight: 60, description: "Cigna OAP Bronze excludes outpatient chest PT for COPD" },
        { name: "Clinical Appropriateness", impact: "neutral", weight: 40, description: "Chest PT is clinically appropriate but not covered benefit" },
      ],
      missingInfo: [],
      policyReferences: [
        { id: "pol-005", title: "Respiratory Therapy Coverage", section: "Section 2.8 - Exclusions", relevanceScore: 88, excerpt: "Outpatient chest physical therapy is excluded from coverage for chronic obstructive pulmonary disease under bronze-tier plans." },
      ],
      generatedAt: "2025-08-15T08:00:00Z",
      modelVersion: "PriorAuth-AI v2.4.1",
    },
    auditLog: [
      { id: "aud-011", action: "Case Submitted", performedBy: "Dr. Thomas Nguyen", role: "Requesting Provider", timestamp: "2025-08-14T09:00:00Z", details: "PA request submitted" },
      { id: "aud-012", action: "AI Triage Completed", performedBy: "PriorAuth AI v2.4.1", role: "AI System", timestamp: "2025-08-15T08:00:00Z", details: "AI recommendation: Deny (79% confidence)" },
      { id: "aud-013", action: "Final Decision - Denied", performedBy: "Dr. Sarah Kim", role: "Medical Director", timestamp: "2025-08-15T11:30:00Z", details: "Denied per plan exclusion. Denial letter sent to provider." },
    ],
  },
  {
    id: "auth-005",
    caseNumber: "PA-2025-08-3344",
    patient: { id: "p-005", name: "Emily Rodriguez", dob: "1991-07-04", memberId: "HUM-3344-881", groupId: "GRP-62110", plan: "Humana HMO Plus", payer: "Humana", gender: "Female", phone: "(305) 555-0499", address: "2200 NW 7th Ave, Miami, FL 33127", primaryCare: "Dr. Carlos Vega" },
    provider: { id: "prov-005", name: "Dr. Maria Santos, MD", npi: "6677889900", specialty: "Dermatology", organization: "Jackson Health System", phone: "(305) 585-1111", fax: "(305) 585-1112", address: "1611 NW 12th Ave, Miami, FL 33136", taxId: "65-6677889" },
    diagnoses: [{ code: "L40.0", description: "Psoriasis vulgaris", type: "primary" }],
    procedures: [{ code: "J0885", description: "Injection, epoetin alfa (non-ESRD use), per 1000 units - Humira", modifier: "", quantity: 2, serviceDate: "2025-09-10", placeOfService: "11 - Office" }],
    status: "Pending Review",
    priority: "normal",
    riskLevel: "medium",
    submittedAt: "2025-08-17T07:00:00Z",
    updatedAt: "2025-08-17T07:00:00Z",
    dueDate: "2025-08-21T17:00:00Z",
    assignedTo: undefined,
    clinicalNotes: "Moderate-to-severe plaque psoriasis. Failed topical and phototherapy. Requesting Humira.",
    documents: [{ id: "doc-008", name: "Dermatology Consultation.pdf", type: "clinical_note", uploadedAt: "2025-08-17T07:00:00Z", uploadedBy: "Dr. Maria Santos", size: "940 KB" }],
    aiRecommendation: undefined,
    auditLog: [
      { id: "aud-014", action: "Case Submitted", performedBy: "Dr. Maria Santos", role: "Requesting Provider", timestamp: "2025-08-17T07:00:00Z", details: "PA request submitted, awaiting AI triage" },
    ],
  },
];

export const MOCK_KPIS: KPIMetric[] = [
  { label: "Total Cases Today", value: 142, change: 12, changeLabel: "vs yesterday", trend: "up", icon: "FileText" },
  { label: "Avg. Decision Time", value: "2.4h", change: -18, changeLabel: "vs last week", trend: "down", icon: "Clock" },
  { label: "Auto-Approval Rate", value: "68%", change: 5, changeLabel: "vs last month", trend: "up", icon: "CheckCircle" },
  { label: "Pending Review", value: 38, change: -8, changeLabel: "vs yesterday", trend: "down", icon: "AlertCircle" },
  { label: "AI Accuracy", value: "94.2%", change: 2, changeLabel: "this quarter", trend: "up", icon: "Brain" },
  { label: "Cases Denied", value: 14, change: 3, changeLabel: "vs yesterday", trend: "up", icon: "XCircle" },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n-001", title: "Urgent Case Assigned", message: "Case PA-2025-08-4821 requires immediate review — due in 2 hours", type: "warning", timestamp: "2025-08-17T14:00:00Z", read: false, caseId: "auth-001" },
  { id: "n-002", title: "AI Triage Complete", message: "Case PA-2025-08-9910 has been triaged. 3 missing items detected.", type: "info", timestamp: "2025-08-17T13:50:00Z", read: false, caseId: "auth-003" },
  { id: "n-003", title: "Case Approved", message: "Case PA-2025-08-2231 was approved by Dr. Michael Torres", type: "success", timestamp: "2025-08-16T16:45:00Z", read: true, caseId: "auth-002" },
  { id: "n-004", title: "Case Denied", message: "Case PA-2025-08-7734 was denied due to plan exclusion", type: "error", timestamp: "2025-08-15T11:30:00Z", read: true, caseId: "auth-004" },
  { id: "n-005", title: "Policy Update", message: "MS therapy policy updated — 12 active cases may be affected", type: "warning", timestamp: "2025-08-15T09:00:00Z", read: true },
];

export const CHART_DAILY_VOLUME = [
  { date: "Aug 11", submitted: 118, approved: 72, denied: 18, pending: 28 },
  { date: "Aug 12", submitted: 134, approved: 81, denied: 22, pending: 31 },
  { date: "Aug 13", submitted: 109, approved: 68, denied: 15, pending: 26 },
  { date: "Aug 14", submitted: 128, approved: 79, denied: 19, pending: 30 },
  { date: "Aug 15", submitted: 142, approved: 91, denied: 21, pending: 30 },
  { date: "Aug 16", submitted: 138, approved: 87, denied: 20, pending: 31 },
  { date: "Aug 17", submitted: 142, approved: 86, denied: 14, pending: 42 },
];

export const CHART_BY_SPECIALTY = [
  { specialty: "Orthopedics", count: 34, color: "#2563EB" },
  { specialty: "Oncology", count: 28, color: "#7C3AED" },
  { specialty: "Neurology", count: 22, color: "#DB2777" },
  { specialty: "Cardiology", count: 19, color: "#059669" },
  { specialty: "Pulmonology", count: 16, color: "#D97706" },
  { specialty: "Dermatology", count: 12, color: "#DC2626" },
  { specialty: "Other", count: 11, color: "#6B7280" },
];

export const CHART_TURNAROUND = [
  { bucket: "< 1h", count: 18 },
  { bucket: "1-2h", count: 31 },
  { bucket: "2-4h", count: 44 },
  { bucket: "4-8h", count: 28 },
  { bucket: "8-24h", count: 16 },
  { bucket: "> 24h", count: 5 },
];
